### ISSUE TITLE
Cannot specify multiple items on the classpath when using CLI

### ISSUE THREAD

**Issue by RadikalJin** [alfasoftware/astra#14]
**Describe the bug**
Cannot specify multiple items on the classpath when using CLI.

**To Reproduce**
1. Follow the steps from the [CLI README](https://github.com/alfasoftware/astra/tree/main/astra-cli) to use the CLI
2. Attempt to specify more than one classpath parameter item

**Expected behavior**
Both classpath parameter items are accepted

**Actual behaviour**
Only one can be used.

**Additional context**
Attempted to use delimiters including semi-colon, comma and blanks, and wrapping with quotes, but none successful. It may be that the [parameter in the refactor](https://github.com/alfasoftware/astra/blob/1a262031db6dae9d3b6ccf3cee37f06a091edba9/astra-cli/src/main/java/org/alfasoftware/astracli/commandline/AstraMethodInvocation.java#L81) requires a property for the delimiter.

**Comment by Arraying** [comment]
Have you tried repeating the same option multiple times with different values? Picoli's [repeated options](https://picocli.info/quick-guide.html#_repeated_options) seem to indicate that you can just repeat, for example:

```astra method --fqType com.example.Foo --name getFoo --newname getBar --parameters= --cp C:\Users\ExampleUser\.m2\repository\com\example\example-impl\example-impl-1.0.jar --cp C:\Users\ExampleUser\.m2\repository\com\foo\foo-impl\foo-impl-1.0.jar --directory C:/Code/CodeBase```

By default, it seems that Picocli's `Option` handles splitting by assigning a regular expression of split characters to `split`. By default, it returns the empty string. That seems to be the problem, because: `@return a regular expression to split option parameter values or {@code ""} if the value should not be split`. So, it appears that Picocli is not attempting to split in the first place.

Let me know if specifying the option multiple times works. I can also PR a fix for the latter suggestions sometime in the near future, perhaps that will make user interaction easier. Intuitively, I'm thinking `[,;]` might be a good regular expression for accepted delimiters, but let me know what you think.

**Comment by RadikalJin** [comment]
Excellent, thanks for pointing that out @Arraying!

Testing with an example like you've given above, Astra is provided multiple classpaths. 

That suggestion sounds great - splitting on `;` would be very useful!

**Comment by RadikalJin** [comment]
Fixed by #49
